name: configure
description: Configure to Toss Payments workflows
inputs:
  npm_token:
    description: 'Toss Payments npm Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: GitHub Profile 설정
      run: |
        git config user.name "tosspayments-bot"
        git config user.email "70372587+tosspayments-bot@users.noreply.github.com"
      shell: bash
    - name: NPM Token 설정
      run: echo //registry.npmjs.org/:_authToken=${{ inputs.npm_token }} | tee .npmrc $HOME/.npmrc > /dev/null
      shell: bash
