name: CI

on:
  push:
    branches:
      - 'master'
      - 'beta'
      - 'alpha'
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Toss Payments 공통 설정
        uses: ./.github/actions/configure
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
      - name: Node.js 환경 설정
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: 테스트
        run: yarn test
      - name: 릴리즈
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha'
        run: |
          yarn build
          yarn semantic-release
